---
title: "Aishvien Nagendran_Intermediate_R_Assignment"
format: html
---

## Part 1: R Basics & Tidyverse Essentials
```{r}

#| warning = FALSE

#Saving the movies data set and inspecting it

library(ggplot2)
library(dplyr)
library(tidyr)

movies <- ggplot2movies::movies

str(movies)
class(movies)
typeof(movies)

```

# Questions 3-4
```{r}
# Question 3 Creating a subset of the movies dataset called movies_final. Removed columns r1-r10

movies_final <- movies |> select(-c(r1,r2,r3,r4,r5,r6,r7,r8,r9,r10))

# Question 4a Created a singular genre column, removed films from genres that it did not belong to
movies_final <- movies_final |>
  mutate(across(.cols = c(Action, Animation,Comedy,Drama,Documentary,Romance,Short),
 .fns = ~ ifelse(.x == 1, cur_column(), NA_character_)                                                   )) |>
  unite(
    col = "genre",
    c(Action, Animation, Comedy, Drama, Documentary, Romance, Short),
    sep = ", ",
    na.rm = TRUE
  )
#| you need the tiydr package to use the unite function
#| english translation of code above: take the genre columns and if the value inside the column is
#| 1 take the name of the column. Then combine multiple columns under one column called "genre" and
#| merge them into a single string

str(movies_final) # I used structure function to check if it worked, and it did!

# Question 4b, Omitted missing values in genre column, split rows into unique film-genres 
movies_genre_ratings <- movies_final |> 
  filter(genre != "" & !is.na(genre)) |> 
  tidyr::separate_longer_delim(genre, delim = ", ") |>
  group_by(genre) |> summarise(mean_rating = mean(rating, na.rm = TRUE))
# On average, Documentary, Animation, and Short films have the highest rating while Drama, Comedy, and action have the lowest rating


```

# Question 5a-5b
```{r}
#| label: fig-movies-year-rating

movies_final |> ggplot(aes(x = year, y = rating)) + 
  geom_point() +
  theme_light() + 
  labs(x = "Year", y = "Rating", title = "Film Year and Rating Graph")

#| label: fig-movies-year-rating-line
movies_final |> ggplot(aes(x = year, y = rating)) + 
  geom_line() +
  theme_light() + 
  labs(x = "Year", y = "Rating", title = "Film Year and Rating Graph")

#| label: fig-movies-year-mpaa
movies_final |> ggplot(aes(x = year, y = rating, color = mpaa )) + 
  geom_point() +
  theme_light() + 
  labs(x = "Year", y = "Rating", title = "Film Year and Rating Graph")


#| There seems to be missing data in the mpaa section

```

## Part 2: Functions, Iterations, and Debugging
```{r}
# Question 6a Creating a Roll Dice Function

library(glue)

roll_dice <- function(d = 20, num_rolls)
   return (sample(1:d, num_rolls, replace = TRUE))
  
print(roll_dice(10, 2))

#Question 6b, modifying Roll Dice Function
roll_dice2 <- function(d = 20, num_rolls) {
  
  if(d < 0 ) warning("Value Error: Please input a positive integer")
  if(num_rolls < 0) warning("Value Error: Please input a positive integer")
  rolls <- sample(1:d, num_rolls, replace = TRUE)
  print(glue("You rolled a {num_rolls} d{d} dice: {paste(rolls, collapse = ', ')}. Sum: {sum(rolls)}"))
  return(rolls)
}

rolls <- roll_dice2(10,100)
```

# Question 7-8b
```{r}

#Question 7a
num_sols <- function(a, b, c) {
  discriminant <- b^2 - 4*a*c
if (discriminant < 0) return("There are no real solutions")
if (discriminant == 0) return("There is one real solution")
if (discriminant > 0) return("There are two real solutions")

  
}
print(num_sols(1,10,2))


#Question 7b
quad_solve <- function(a, b, c){
  discriminant <- b^2 - 4*a*c
if (discriminant < 0) return("There are no real solutions")
if (a == 0) stop("Value error: Input a non-zero integer")
  
plus_squarer <-  (-b + sqrt(discriminant)/ 2*a) #Had to create the minus and plus sign since R has no operator
minus_squarer <- (-b - sqrt(discriminant)/ 2*a)
  
return(c(root1 = plus_squarer, root2 = minus_squarer))

 
}
print(quad_solve(1,10,2))


#Question 8a
collatz <- function(n) {
  steps <- 1
  while (n > 2) {         # I realized that the while condition had to be n < 2 for collatz(2) to work
    if (n %% 2 == 0) {
      n <- n / 2
    } else {
      n <- 3*n + 1
    }
    steps <- steps + 1
  }
  steps
}

collatz(37) #Returns 21






```
  

